// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/arifseft/article-api/domain"
	mock "github.com/stretchr/testify/mock"
)

// ArticleSearch is an autogenerated mock type for the ArticleSearch type
type ArticleSearch struct {
	mock.Mock
}

// IndexArticle provides a mock function with given fields: ctx, a
func (_m *ArticleSearch) IndexArticle(ctx context.Context, a *domain.Article) error {
	ret := _m.Called(ctx, a)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Article) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchArticle provides a mock function with given fields: ctx, payload
func (_m *ArticleSearch) SearchArticle(ctx context.Context, payload domain.ArticleSearchPayload) ([]domain.Article, error) {
	ret := _m.Called(ctx, payload)

	var r0 []domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, domain.ArticleSearchPayload) []domain.Article); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ArticleSearchPayload) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
