// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/arifseft/article-api/domain"
	mock "github.com/stretchr/testify/mock"
)

// ArticleEvent is an autogenerated mock type for the ArticleEvent type
type ArticleEvent struct {
	mock.Mock
}

// PublishArticleCreated provides a mock function with given fields: ctx, a
func (_m *ArticleEvent) PublishArticleCreated(ctx context.Context, a domain.Article) error {
	ret := _m.Called(ctx, a)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Article) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeArticleCreated provides a mock function with given fields: ctx, f
func (_m *ArticleEvent) SubscribeArticleCreated(ctx context.Context, f func(domain.Article)) error {
	ret := _m.Called(ctx, f)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(domain.Article)) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
