// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/arifseft/article-api/domain"
	mock "github.com/stretchr/testify/mock"
)

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type ArticleRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, keyword, author
func (_m *ArticleRepository) Fetch(ctx context.Context, keyword string, author string) ([]domain.Article, error) {
	ret := _m.Called(ctx, keyword, author)

	var r0 []domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Article); ok {
		r0 = rf(ctx, keyword, author)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, keyword, author)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, a
func (_m *ArticleRepository) Store(ctx context.Context, a *domain.Article) error {
	ret := _m.Called(ctx, a)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Article) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
