// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/arifseft/article-api/domain"
	mock "github.com/stretchr/testify/mock"
)

// ArticleUsecase is an autogenerated mock type for the ArticleUsecase type
type ArticleUsecase struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, keyword, author
func (_m *ArticleUsecase) Fetch(ctx context.Context, keyword string, author string) ([]domain.Article, error) {
	ret := _m.Called(ctx, keyword, author)

	var r0 []domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Article); ok {
		r0 = rf(ctx, keyword, author)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, keyword, author)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *ArticleUsecase) Store(_a0 context.Context, _a1 *domain.Article) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Article) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
