version: '3.7'

services: 
  app:
    hostname: article_api_development
    container_name: article_api_app
    depends_on: 
      - mysql
      - es01
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      DEBUG: "true"
      SERVING_PORT: "*:9090"
      DB_HOST: article_api_db
    volumes: 
      - ./config.json:/app/config.json
    ports:
      - 9090:9090
    tty: true
    networks: 
      - article_api_development

  mysql:
    image: mysql:5.7
    container_name: article_api_db
    volumes:
      - ./sql/article.sql:/docker-entrypoint-initdb.d/article.sql
      - article_api:/usr/local/mysql/data
    environment:
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=db_articles
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_TCP_PORT=3307
    ports:
      - 3307:3307
    networks:
      - article_api_development

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: article_api_es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - article_api_development

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: article_api_es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - article_api_development

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: article_api_es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - article_api_development

  nats01:
    image: nats:2.1.9
    container_name: article_api_nats01
    ports:
      - "8222:8222"
    networks:
      - article_api_development

  nats02:
    image: nats:2.1.9
    container_name: article_api_nats02
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - article_api_development
    depends_on: 
      - "nats01"

  nats03:
    image: nats:2.1.9
    container_name: article_api_nats03
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - article_api_development
    depends_on: 
      - "nats01"


volumes: 
  article_api:
  data01:
  data02:
  data03:

networks:
  article_api_development:
